<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

//Dashboard Nav
remove_action( 'genesis_after_header', 'genesis_do_subnav' );
add_action( 'genesis_before_header', 'genesis_do_subnav' );


add_filter( 'genesis_pre_get_option_site_layout', '__genesis_return_full_width_content' );
add_action( 'genesis_before_loop', 'genesis_do_search_title' );
/**
 * Echo the title with the search term.
 *
 * @since 1.9.0
 */
function genesis_do_search_title() {

	$title = sprintf( '<div class="archive-description"><h1 class="archive-title">%s %s</h1></div>', apply_filters( 'genesis_search_title_text', __( 'Search Results for:', 'genesis' ) ), get_search_query() );

	echo apply_filters( 'genesis_search_title_output', $title ) . "\n";

}


remove_action('genesis_loop', 'genesis_do_loop');
add_action('genesis_loop','init_results');
function init_results(){ ?>

	<table class="orders">
 
 
 
    <tr>
        <th></th>
        <th>Order Date</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Product</th>
        <th>Brand</th>
    <?php if ( have_posts() ) : while ( have_posts() ) : the_post(); ?>
	
	<tr>
	    <td><?php the_title();?></td>
	     <td>
            <?php	if ( get_field( 'order_date' ) ) {
		echo '<p>' . get_field( 'order_date' )  . '</p>';
	}?>
        </td>
        <td>
            <?php	if ( get_field( 'first_name' ) ) {
		echo '<p>' . get_field( 'first_name' )  . '</p>';
	}?>
        </td>
            <td>
            <?php	if ( get_field( 'last_name' ) ) {
		echo '<p>' . get_field( 'last_name' )  . '</p>';
	}?>
        </td>
  
         <td>
            <?php	if ( get_field( 'product' ) ) {
		echo '<p>' . get_field( 'product' )  . '</p>';
	}?>
        </td>
        
          <td>
            <?php	if ( get_field( 'brand' ) ) {
		echo '<p>' . get_field( 'brand' )  . '</p>';
	}?>
        </td>
        
  
        
        <td>
           <a class="button" href="<?php the_permalink();?>">View</a>
        </td>
        
    </tr>


<?php endwhile; else : ?>
	<p><?php _e( 'Sorry, no posts matched your criteria.' ); ?></p>
<?php endif; ?>

</table>
<?php }

genesis();

?>